# Generated by Django 3.2.5 on 2021-07-29 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bookadd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(max_length=100)),
                ('publication', models.CharField(max_length=100)),
                ('serialno', models.IntegerField()),
                ('edition', models.CharField(max_length=100)),
                ('fineamt', models.IntegerField()),
            ],
            options={
                'db_table': 'bookmaster',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='bookissuedetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookmasterid', models.CharField(max_length=100)),
                ('issueuptodate', models.DateField()),
            ],
            options={
                'db_table': 'bookissuedetails',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='bookissuemaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smid', models.CharField(max_length=100)),
                ('totalnobook', models.IntegerField()),
            ],
            options={
                'db_table': 'bookissuemaster',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='bookissuetempd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(max_length=100)),
                ('issueuptodate', models.DateField()),
            ],
            options={
                'db_table': 'bookissuetemp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='studentadd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rollno', models.IntegerField()),
                ('fname', models.CharField(max_length=100)),
                ('mname', models.CharField(max_length=100)),
                ('mobileno', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
            ],
            options={
                'db_table': 'student',
                'managed': False,
            },
        ),
    ]
